import { api } from '../utils/api.js';

export interface PushStatus {
  isSupported: boolean;
  permission: NotificationPermission | 'unsupported';
  isSubscribed: boolean;
}

/**
 * Utility to convert base64 URL safe string to Uint8Array for PushManager
 */
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, '+')
    .replace(/_/g, '/');

  const rawData = window.atob(base64);
  const buffer = new ArrayBuffer(rawData.length);
  const outputArray = new Uint8Array(buffer);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Check if the current browser environment supports Service Workers, Push, and Notifications
 */
export function isPushNotificationSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    'serviceWorker' in navigator &&
    'PushManager' in window &&
    'Notification' in window
  );
}

/**
 * Register or return existing PollHub service worker
 */
export async function registerServiceWorker(): Promise<ServiceWorkerRegistration | null> {
  if (!isPushNotificationSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/'
    });
    return registration;
  } catch (err) {
    console.error('[PushService] Service worker registration failed:', err);
    return null;
  }
}

/**
 * Get current browser PushSubscription if one exists
 */
export async function getCurrentPushSubscription(): Promise<PushSubscription | null> {
  if (!isPushNotificationSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.ready;
    return await registration.pushManager.getSubscription();
  } catch (err) {
    console.error('[PushService] Error reading push subscription:', err);
    return null;
  }
}

/**
 * Check overall push status (support, permission, active subscription)
 */
export async function getPushNotificationStatus(): Promise<PushStatus> {
  if (!isPushNotificationSupported()) {
    return {
      isSupported: false,
      permission: 'unsupported',
      isSubscribed: false
    };
  }

  const permission = Notification.permission;
  const subscription = await getCurrentPushSubscription();

  return {
    isSupported: true,
    permission,
    isSubscribed: !!subscription && permission === 'granted'
  };
}

/**
 * Request notification permission, register push subscription, and send to backend
 */
export async function subscribeToPushNotifications(): Promise<{ success: boolean; message?: string }> {
  if (!isPushNotificationSupported()) {
    return { success: false, message: 'Push notifications are not supported in this browser.' };
  }

  try {
    // 1. Request user permission
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      return {
        success: false,
        message: permission === 'denied'
          ? 'Notifications are blocked. Please enable them in your browser settings.'
          : 'Notification permission was dismissed.'
      };
    }

    // 2. Ensure Service Worker is registered and ready
    await registerServiceWorker();
    const registration = await navigator.serviceWorker.ready;

    // 3. Fetch VAPID public key from backend
    const vapidRes = await api.get('/notifications/vapid-key');
    const vapidPublicKey = vapidRes.data?.data?.publicKey;

    if (!vapidPublicKey) {
      throw new Error('VAPID public key was not returned by server.');
    }

    const applicationServerKey = urlBase64ToUint8Array(vapidPublicKey);

    // 4. Check for existing subscription or create new
    let subscription = await registration.pushManager.getSubscription();
    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: applicationServerKey as any
      });
    }

    const subscriptionJson = subscription.toJSON();
    if (!subscriptionJson.endpoint || !subscriptionJson.keys?.p256dh || !subscriptionJson.keys?.auth) {
      throw new Error('Invalid subscription generated by browser PushManager.');
    }

    // 5. Send subscription payload to authenticated backend endpoint
    await api.post('/notifications/subscribe', {
      endpoint: subscriptionJson.endpoint,
      keys: {
        p256dh: subscriptionJson.keys.p256dh,
        auth: subscriptionJson.keys.auth
      },
      userAgent: navigator.userAgent
    });

    return { success: true, message: 'Push notifications enabled successfully!' };
  } catch (error: any) {
    console.error('[PushService] Failed to subscribe to push notifications:', error);
    const msg = error.response?.data?.message || error.message || 'Failed to enable notifications.';
    return { success: false, message: msg };
  }
}

/**
 * Unsubscribe from push notifications locally and notify backend
 */
export async function unsubscribeFromPushNotifications(): Promise<{ success: boolean; message?: string }> {
  if (!isPushNotificationSupported()) {
    return { success: false, message: 'Push notifications are not supported.' };
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const endpoint = subscription.endpoint;
      // 1. Notify backend to deactivate subscription
      try {
        await api.post('/notifications/unsubscribe', { endpoint });
      } catch (err) {
        console.warn('[PushService] Backend unsubscribe failed, proceeding with local unsubscribe:', err);
      }

      // 2. Unsubscribe locally in browser
      await subscription.unsubscribe();
    } else {
      // Still notify backend to deactivate all for user
      await api.post('/notifications/unsubscribe', {});
    }

    return { success: true, message: 'Push notifications disabled.' };
  } catch (error: any) {
    console.error('[PushService] Failed to unsubscribe:', error);
    return { success: false, message: 'Failed to disable notifications.' };
  }
}
